{% set name = "cmake_format" %}
{% set version = "0.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82f0ef16236225cb43f45bfb6983ef7f6f72634727a1a6c26290402527bdd793

build:
  number: 0
  noarch: python
  entry_points:
    - cmake-format=cmake_format.__main__:main
    - cmake-annotate=cmake_format.annotate:main
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - cmake_format
    - cmake_format.command_tests
    - cmake_format.parse_funs
  commands:
    - cmake-format --help
    - cmake-annotate --help

about:
  home: https://github.com/cheshirekow/cmake_format
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Can format your listfiles so they don't look like crap

extra:
  recipe-maintainers:
    - xhochy
