{% set name = "cmake_format" %}
{% set version = "0.5.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 10107e7ddb8011057e784d390c28614c0222ccb2d8026ed842fe4441feca5c92

build:
  number: 0
  noarch: python
  entry_points:
    - cmake-format=cmake_format.__main__:main
    - cmake-annotate=cmake_format.annotate:main
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cmake_format
    - cmake_format.command_tests
    - cmake_format.parse_funs
  commands:
    - cmake-format --help
    - cmake-annotate --help

about:
  home: "https://github.com/cheshirekow/cmake_format"
  license: GPL-3
  license_family: GPL
  license_file: LICENSE
  summary: "Can format your listfiles so they don't look like crap"

extra:
  recipe-maintainers:
    - xhochy
