travis:
  secure:
    BINSTAR_TOKEN: NBUchhoS+0RcjEtCsYiaWM/NzW/7LS1r1etnftlX2oKAddrO2DuYBeU6Gxl6PhSb4YKlbfHLhYHIpOmFMuL3iimGqWa7G6cRID+LAXTT5dgOprxVgkhDK60a0t3TKwO7/T8h/WWA/sbXjCfZ2xwKgqKkC7+SsXnvcYfGdu5pYRbymImyGEkqhkNV0GKFNaORAFEvFrtCKlLDCrX47eMLQqR53wkenXHfOiStG7Wu//NXTNO2C3gxNlPPD3BnvKDbUGwzgJ0hhX5p0pMhZNEto5ew5TJnnQLkyYZIA0zY7/SZVNxYwvRTuha+EUs5KIO8biJAU/yYnqPEwwIEHRLc0JrsXIAyYKWQiAZvwE3A6D1m0IV45jOKSkwHnd3fFOk2WhIk/67/Eagt522lMY/0c45/4tjV5P658wwZI7SQHzAQu5NtPlXcgQQwNKrEswKqwOjWzF8uED0ifDyqnT+QVe0j6XkZjpoRnS0c6BTu4KujV3tmqAv0v2oo1fqnpQYRi9nyf5DYT1gwMQVttz9Z45MKpNjBcRhUa8IZDCJp9yT93/WY7+wUCM1/akerxObvMu15fyELWR2D3Gd3dZj7VtNuebiyZq7I7XsmZGyRGNr4XTCaV9omr3NXnCwxRCdrh1Daeg6lEfU5Wbd+7128ibEAWvjMn3DBTiL2BLRErxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
